### ISSUE TITLE
error in testing code for tile segmentation

### ISSUE THREAD

**Issue by dineshreddy91** [MPI-IS/bilateralNN#1]
The following error message
AttributeError: 'Net' object has no attribute 'load_blobs_from'

I guess we need to include barrista or is there a work around for it?

**Comment by varunjampani** [comment]
Yes, 'load_blobs_from' is a function from Barrista which loads the trained filter weights. In the present script, this line is somewhat redundant as the previous line already loads the filter weights. So, this line in predict.py can be omitted. Thanks for reporting.
