### ISSUE TITLE
CUDA error when  tried to train Bilateral Neural Networks 

### ISSUE THREAD

**Issue by codepujan** [MPI-IS/bilateralNN#10]
I was trying to train BNN  on my system and it  gives me an error just after Network initialization has been done . The sequences goes sth like : 

This network produces output loss
I0912 13:17:43.730710 23926 net.cpp:255] Network initialization done.
I0912 13:17:43.730861 23926 solver.cpp:56] Solver scaffolding done.

And Then It Stops in this line : 

 Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered

What can I do further to debug this problem or move ahead with it? 
Any help would be great. 

Thanks

**Comment by varunjampani** [comment]
Difficult to debug with just this information. Probably, it has something to do with the incompatibility of your cuDNN or cuda version and caffe. Are you able to successfully run any example test script with permutohedral layers?
