### ISSUE TITLE
What is the difference between Gauss Bilateral and Learned Bilateral?

### ISSUE THREAD

**Issue by chenchr** [MPI-IS/bilateralNN#11]
Hello. Thank you for sharing this awesom works. I have a question about the result in the paper.
![1](https://user-images.githubusercontent.com/10046830/36072219-a6255544-0f56-11e8-8993-e385a72eeb21.PNG)
If we do not consider the implementation, is the difference between ``` gauss bilateral `` and ``` learned bilateral ``` is that the variance of filter in ``` learned bilateral ``` is learnable and is learned from training ? Thanks!

**Comment by varunjampani** [comment]
Sorry for my delayed response. Somehow, I missed this.

'Gauss bilateral' refers to Gaussian filter in high-dimensional space. 'Learned bilateral' filter refers to learned filter weights (not just the variance of the filter). You can think of this as learning a high-dimensional convolution filter, just like in standard CNNs. Standard CNNs operate in 2D or 3D space and this work makes it feasible to do convolution in higher dimensional spaces.

**Comment by chenchr** [comment]
@varunjampani Thanks for your reply. Maybe I have misunderstanding...  Do you mean that the learned bilateral filter is not just variance learnable but the weight ? Therefore it directly output the weight,  and has no need to calculate the exponential of feature difference and then normalize?

**Comment by varunjampani** [comment]
Yes, the 'learned' bilateral filter is not just learned variance, but the filter weights in high-dimensional space. You can think of this as a general convolution in high-dimensions. For both non-learned Gaussian and learned filters, we use normalization to account for non-uniformly sampled sparse data in high-dimensions.

**Comment by chenchr** [comment]
Thanks for your reply.
