### ISSUE TITLE
Examples for visualizing lattice

### ISSUE THREAD

**Issue by laoreja** [MPI-IS/bilateralNN#12]
I noticed that there is an visualize_lattice option in the layer parameters. How to utilize this option and do visualization? can you provide some guidance?

Thank you!

**Comment by varunjampani** [comment]
'visualize_lattice = True' will make all the barycentric coordinates equal inside each lattice. In other words, if we pass random input (bottom-1) with meaningful lattice features (bottom-2 and bottom-3, say XYRGB, RGB, XY etc.) and use the layer with 'visualize_lattice = True', those points falling in the same lattice will have same output value. You an assign random unique colors to each output value to visualize which points fall into same simplex. We use this to do the lattice visualization in Figure-2 in the main paper. Is this clear?

**Comment by laoreja** [comment]
Thank you!
