### ISSUE TITLE
Getting error while installing caffe provided here

### ISSUE THREAD

**Issue by musafirsafwan** [MPI-IS/bilateralNN#2]
`nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/bilateralNN/build/tmp_caffe_clone/src/CaffeUpstream/include/caffe/common.cuh(13): error: function "atomicAdd(double *, double)" has already been defined`

`nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).`

`1 error detected in the compilation of "/tmp/tmpxft_00004400_00000000-5_permutohedral.cpp4.ii".
CMake Error at cuda_compile_generated_permutohedral.cu.o.cmake:264 (message):
  Error generating file`
  `/bilateralNN/build/bin/src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_permutohedral.cu.o`

`make[5]: *** [src/caffe/CMakeFiles/cuda_compile.dir/util/cuda_compile_generated_permutohedral.cu.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [tmp_caffe_clone/src/CaffeUpstream-stamp/CaffeUpstream-build] Error 2
make[1]: *** [CMakeFiles/CaffeUpstream.dir/all] Error 2
make: *** [all] Error 2`

Any idea how to fix this?
Thank you.

**Comment by raffienficiaud** [comment]
Thanks for the feedback. What is your operating system and the version of CUDA you are running?

**Comment by musafirsafwan** [comment]
Ubuntu 14.04 and Cuda 8.

**Comment by musafirsafwan** [comment]
I suspect it is because the cuDNN is not getting detected. In the Caffe Configuration Summary shown just before compilation, 'Not found' is shown for cuDNN. I faced the issue when I was installing the original (unpatched) caffe. That time, I used ccmake to add the cuDNN path before compilation and it solved the issue. Here I am not to able to give the cuDNN path using ccmake.

**Comment by musafirsafwan** [comment]
I tried `cmake -DCUDNN_INCLUDE=/usr/local/cuda/include/ -DCUDNN_LIBRARY=/usr/local/cuda/lib64/ ..`, but still getting the same error.

**Comment by varunjampani** [comment]
Are you getting the same error when installing some other caffe version? And, did you try 'manual way' of porting the new 'permutohedral' and 'pixel feature' layers into your caffe version?

Like below:

The patching that is performed by cmake is rather a copying of the files from the folder of the bilateralNN to the corresponding folders of Caffe. Caffe will then add the new files into the project.

Alternatively, you can manually copy all but caffe.proto source files in bilateralNN folder to the corresponding locations in your Caffe repository. Then, for merging the caffe.proto file of bilateralNN to your version of the caffe.proto:

1. Copy the lines 382-383 and 854-922 in caffe.proto to the corresponding caffe.proto file in the destination Caffe repository.
2. Change the parameter IDs for PermutohedralParameter and PixelFeatureParameter based on the next available LayerParameter ID in your Caffe.

**Comment by musafirsafwan** [comment]
Hi Varun, thanks for the response.

1. I tried patching the latest caffe version (0.15.13) and while running make command after cmake (I believe I have to run make after running cmake, correct me if I am wrong), I am getting the same error which I am getting while installing the already patched caffe provided here.

2. I tried the manual way of porting the layers into my caffe version. After copying the files and changing the parameter IDs, I recompile my caffe version (I believe that I have to recompile caffe after manually porting the layers. Correct me if I am wrong). While recompiling, I am getting some warnings in the start and an error in the end.

These are the warnings I am getting:
```
src/caffe/layers/permutohedral_layer.cpp:153:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel
 ^
src/caffe/layers/permutohedral_layer.cpp:157:0: warning: ignoring #pragma omp for [-Wunknown-pragmas]
       #pragma omp for
 ^
src/caffe/layers/permutohedral_layer.cpp:342:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel
 ^
src/caffe/layers/permutohedral_layer.cpp:348:0: warning: ignoring #pragma omp for [-Wunknown-pragmas]
 #pragma omp for
 ^
src/caffe/layers/permutohedral_layer.cpp:426:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
   #pragma omp parallel
 ^
src/caffe/layers/permutohedral_layer.cpp:439:0: warning: ignoring #pragma omp for [-Wunknown-pragmas]
     #pragma omp for
 ^
src/caffe/layers/permutohedral_layer.cpp:463:0: warning: ignoring #pragma omp critical [-Wunknown-pragmas]
     #pragma omp critical
 ^
```
And this is the error I am getting:
```
1 error detected in the compilation of "/tmp/tmpxft_00002f72_00000000-5_permutohedral.cpp4.ii".
make: *** [.build_release/cuda/src/caffe/util/permutohedral.o] Error 1
```

I don't know what changes should I make and any help is greatly appreciated.

**Comment by raffienficiaud** [comment]
The warnings that you are getting indicate a lack of openmp support for your compiler. Would you please:

* indicate your compiler? maybe this is a `clang` issue
* run `make VERBOSE=1` instead of just `make` such that we can see the full command line.

Thanks

**Comment by raffienficiaud** [comment]
I will add your changes! I am closing the issue then.
Thanks for helping out!
