### ISSUE TITLE
Accessing the Permutohedral Layer  to define a Net through Python Code

### ISSUE THREAD

**Issue by codepujan** [MPI-IS/bilateralNN#8]
I am designing my Caffe Net through python . Just like Importing any other Caffe Layers , is there any way we can import the Permutohedral layer in Python Code  . 

Thank you !!

**Comment by varunjampani** [comment]
Yes, you can use pycaffe to specify any layer in caffe, including 'permutohedral' layer. We used this layer for propagating information across video frames. You can find an example net specification with permutohedral layers here: https://github.com/varunjampani/video_prop_networks/blob/master/seg_propagation/create_online_net.py
